- name: Tasks of Docker 
  become: true
  block:
    - name: Update apt packages
      apt:
        update_cache: yes
        cache_valid_time: 86400
      tags: docker

    - name: Update Docker.io package
      apt:
        name: docker.io
        state: latest
      tags: docker